---
title: "R Notebook"
output: html_notebook
---

Environment Setup

```{r Library, message=FALSE}
library(tidyverse)
library(lubridate)
library(anytime)
library(stringr)
library(data.table)
sessionInfo()
```


```{r Load Data}
fileUrl <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2"
fname <- c("./data/maindf.csv.bz2")

if(!file.exists("data")){
        dir.create("data")
}

download.file(fileUrl,destfile="./data/maindf.csv.bz2",method="curl")



maindf <- read.csv("1.csv", header = TRUE, na.strings=c("","NA"))
dateDownloaded <- date()
dateDownloaded
```


```{r}
df <- maindf

```

```{r, cache=TRUE}
summary(df$BGN_DATE)

```




```{r combine }
df$BGN_DATE <- as.POSIXct(df$BGN_DATE,format="%m/%d/%Y")
df$BGN_TIME <- as.integer(df$BGN_TIME) 
CompleteDF<-df %>% 
    mutate(DateTime = paste(BGN_DATE, sprintf("%04d", BGN_TIME)))
(CompleteDF$DateTime) <- mdy_hm(CompleteDF$DateTime)

```


```{r}
head(CompleteDF)
```





1.  Across the United States, which types of events (as indicated in the EVTYPE variable) are most harmful with respect to population health?

```{r}
NOAA_df <- df %>%  select(STATE, COUNTY,COUNTYNAME,BGN_DATE, BGN_TIME, EVTYPE, PROPDMG, PROPDMGEXP, CROPDMG, CROPDMGEXP, FATALITIES, INJURIES)
```

```{r}
unique(NOAA_df$EVTYPE)
```


```{r}
StateHarm <- NOAA_df %>% group_by(YEAR= year(BGN_DATE))   (STATE, EVTYPE) %>% summarize(INJFATLS = sum(FATALITIES+INJURIES)) %>% arrange(desc(INJFATLS))

```

```{r}
ggplot
```



```{r}
gatherpairs <- function(data, ..., 
                        xkey = '.xkey', xvalue = '.xvalue',
                        ykey = '.ykey', yvalue = '.yvalue',
                        na.rm = FALSE, convert = FALSE, factor_key = FALSE) {
  vars <- quos(...)
  xkey <- enquo(xkey)
  xvalue <- enquo(xvalue)
  ykey <- enquo(ykey)
  yvalue <- enquo(yvalue)

  data %>% {
    cbind(gather(., key = !!xkey, value = !!xvalue, !!!vars,
                 na.rm = na.rm, convert = convert, factor_key = factor_key),
          select(., !!!vars)) 
  } %>% gather(., key = !!ykey, value = !!yvalue, !!!vars,
               na.rm = na.rm, convert = convert, factor_key = factor_key)
}
```


```{r}
df %>% 
  gatherpairs(FATALITIES, STATE, Petal.Length, Petal.Width) %>% {
  ggplot(., aes(x = .xvalue, y = .yvalue, color = DF$EVTYPE)) +
      geom_point() + 
      geom_smooth(method = 'lm') +
      facet_wrap(.xkey ~ .ykey, ncol = length(unique(.$.ykey)), scales = 'free', labeller = label_both) +
      scale_color_brewer(type = 'qual')
}
```



2.  Across the United States, which types of events have the greatest economic consequences?




